export const mediaData = {
    press: [
        {
            id: 1,
            title: 'Smart City Sweden Supports Waste Management Project...',
            date: '12 March 2024',
            description: 'The Government of Sweden has through its export platform Smart City Sweden, approved financing support to the....',
            tags: ['Waste to Energy', 'Climate Change'],
        },
        {
            id: 2,
            title: 'Swap Station, Others, To Deploy Electric Vehicle ...',
            date: '16 May 2024',
            description: 'Blackaion Capital and FundCo Capital Managers who are the co-sponsors of Swap Station Mobility, believe the operational cost of battery swapping ...',
            images: ['/project-1.png', '/project-2.png'],
        },
        {
            id: 3,
            title: 'Capsa Technology records over 300% growth, supports ...',
            date: '22 Nov 2021',
            description: 'Capsa Technology, Nigeria\\\'s invoice factoring platform, has reported an over 300 percent rise in its transaction volume despite ...',
            tags: ['SME Financing', 'Economics'],
        },
    ],
    blog: [
        {
            id: 1,
            title: 'The Future of Renewable Energy in West Africa',
            slug: 'the-future-of-renewable-energy-in-west-africa',
            date: '10 June 2024',
            description: 'A deep dive into the trends, challenges, and opportunities shaping the renewable energy landscape in the region.',
            tags: ['Renewable Energy', 'Sustainability'],
            image: '/project-1.png',
        },
        {
            id: 2,
            title: 'Smart Cities: How Technology is Reshaping Urban Development',
            slug: 'smart-cities-how-technology-is-reshaping-urban-development',
            date: '28 May 2024',
            description: 'Exploring the role of IoT, AI, and big data in creating more efficient and livable cities.',
            tags: ['Infratech', 'Smart Cities'],
            image: '/project-2.png',
        },
        {
            id: 3,
            title: 'The Power of Public-Private Partnerships in Infrastructure',
            slug: 'the-power-of-public-private-partnerships-in-infrastructure',
            date: '15 May 2024',
            description: 'An analysis of successful PPP models and their impact on large-scale infrastructure projects.',
            tags: ['Investment', 'Partnerships'],
            image: '/project-3.png',
        },
        {
            id: 4,
            title: 'Navigating the Regulatory Landscape for Energy Projects',
            slug: 'navigating-the-regulatory-landscape-for-energy-projects',
            date: '02 May 2024',
            description: 'Key legal and regulatory considerations for developers and investors in the African energy sector.',
            tags: ['Regulation', 'Energy'],
            image: '/project-1.png',
        },
        {
            id: 5,
            title: 'Sustainable Waste Management Solutions for Growing Economies',
            slug: 'sustainable-waste-management-solutions-for-growing-economies',
            date: '18 April 2024',
            description: 'From waste-to-energy to circular economy models, a look at sustainable solutions for waste.',
            tags: ['Sustainability', 'Waste Management'],
            image: '/project-2.png',
        },
        {
            id: 6,
            title: 'The Rise of Digital Infrastructure in Africa',
            slug: 'the-rise-of-digital-infrastructure-in-africa',
            date: '05 April 2024',
            description: 'How data centers, fiber optics, and mobile connectivity are unlocking economic potential.',
            tags: ['Digital Infrastructure', 'Technology'],
            image: '/project-3.png',
        }
    ],
    events: [
        {
            id: 1,
            title: 'Annual Infrastructure Investment Summit',
            slug: 'annual-infrastructure-investment-summit',
            date: '25 July 2024',
            location: 'Lagos, Nigeria',
            focus: 'Investment',
            type: 'Conference',
            description: 'Join us for our annual summit where we discuss the future of infrastructure investment with industry leaders.',
            tags: ['Investment', 'Infrastructure'],
            image: '/project-1.png',
            gallery: ['/project-1.png', '/project-2.png', '/project-3.png', '/project-4.png'],
        },
        {
            id: 2,
            title: 'West Africa Power-Tech Conference',
            slug: 'west-africa-power-tech-conference',
            date: '15 September 2024',
            location: 'Accra, Ghana',
            focus: 'Technology',
            type: 'Exhibition',
            description: 'Exploring innovations in renewable energy and power distribution. A key event for stakeholders in the energy sector.',
            tags: ['Energy', 'Technology'],
            image: '/project-2.png',
            gallery: ['/project-2.png', '/project-2.png', '/project-2.png', '/project-2.png'],
        }
    ],
    upcomingEvents: [
      {
            id: 1,
            title: 'Global Infra-Tech Summit 2025',
            slug: 'global-infra-tech-summit-2025',
            date: '15 October 2025',
            location: 'Dubai, UAE',
            focus: 'Global Infrastructure',
            type: 'Summit',
            description: 'The premier global summit for infrastructure and technology, bringing together leaders from around the world.',
            tags: ['Infra-tech', 'Global'],
            image: '/upcoming-event-1.png',
            gallery: ['/project-1.png', '/project-2.png', '/project-3.png', '/project-4.png'],
        },
        {
            id: 2,
            title: 'Future of Energy Conference',
            slug: 'future-of-energy-conference',
            date: '20 November 2025',
            location: 'Online',
            focus: 'Renewable Energy',
            type: 'Virtual Conference',
            description: 'A virtual conference exploring the future of renewable energy and sustainable power solutions.',
            tags: ['Energy', 'Sustainability'],
            image: '/upcoming-event-2.png',
            gallery: ['/project-1.png', '/project-2.png', '/project-3.png', '/project-4.png'],
        }
    ]
}; 